version: '3.8'

services:

  laravel:
    restart: unless-stopped
    container_name: laravel
    build:
      context: ../
      dockerfile: ./deploy/Dockerfile
    volumes:
      - ../project:/app
    ports:
      - "8080:80"
    networks:
      - laravel
    depends_on:
      - postgres

  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - laravel

  adminer:
    image: adminer
    container_name: adminer-local
    restart: unless-stopped
    networks:
      - laravel
    depends_on:
      - postgres

networks:
  laravel:

volumes:
  pgdata:
